name: Integration tests

# Temporarily disabled on this fork while stress tests are being developed.
# Only manual dispatch is enabled.
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git reference or commit hash to run the workflow against."
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    if: github.event_name != 'schedule' || github.repository == 'awslabs/mountpoint-s3'
    name: Integration
    uses: ./.github/workflows/integration.yml
    with:
      ref: ${{ github.sha }}
